[package]
name = "rtss"
version = "0.1.0"
authors = ["Alex Afshar <contact@alexafshar.com>"]
edition = "2018"

[dependencies]
bigdecimal = "0.0.15"
chrono = "0.4"
diesel = { version = "1.0.0", features = ["postgres", "chrono", "bigdecimal", "numeric"] }
dotenv = "0.9.0"
